name: Run Selenium Test Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

       - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      
    - name: Verify installations
      run: |
        google-chrome --version
        chromedriver --version
        java -version
      - name: Configure WebDriverManager to Use System Driver
        run: |
          echo "webdriver.chrome.driver=/usr/local/bin/chromedriver" > selenium.properties

      - name: Install Dependencies
        run: mvn install -e  # Added -e flag to display full error output in case of failure

      - name: Run Selenium Tests
        run: mvn test
